
seed: 42
paths:
  data_root: data/mini_sample
  outputs: outputs
  weights: outputs
training:
  epochs: 5
  batch_size: 32
  lr: 0.001
  img_size: [64, 64]
  classes: ["A","B","C","D","E"]
transfer:
  img_size: [224, 224]
  backbone: resnet50
landmarks:
  seq_len: 16
  hidden: 128
